/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SellerDashboardRouteImport } from './routes/seller-dashboard'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsProductUpgraderRouteImport } from './routes/tools.product-upgrader'

const SellerDashboardRoute = SellerDashboardRouteImport.update({
  id: '/seller-dashboard',
  path: '/seller-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsProductUpgraderRoute = ToolsProductUpgraderRouteImport.update({
  id: '/tools/product-upgrader',
  path: '/tools/product-upgrader',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/credits': typeof CreditsRoute
  '/explore': typeof ExploreRoute
  '/seller-dashboard': typeof SellerDashboardRoute
  '/tools/product-upgrader': typeof ToolsProductUpgraderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/credits': typeof CreditsRoute
  '/explore': typeof ExploreRoute
  '/seller-dashboard': typeof SellerDashboardRoute
  '/tools/product-upgrader': typeof ToolsProductUpgraderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/credits': typeof CreditsRoute
  '/explore': typeof ExploreRoute
  '/seller-dashboard': typeof SellerDashboardRoute
  '/tools/product-upgrader': typeof ToolsProductUpgraderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/credits'
    | '/explore'
    | '/seller-dashboard'
    | '/tools/product-upgrader'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/credits'
    | '/explore'
    | '/seller-dashboard'
    | '/tools/product-upgrader'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/credits'
    | '/explore'
    | '/seller-dashboard'
    | '/tools/product-upgrader'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CreditsRoute: typeof CreditsRoute
  ExploreRoute: typeof ExploreRoute
  SellerDashboardRoute: typeof SellerDashboardRoute
  ToolsProductUpgraderRoute: typeof ToolsProductUpgraderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seller-dashboard': {
      id: '/seller-dashboard'
      path: '/seller-dashboard'
      fullPath: '/seller-dashboard'
      preLoaderRoute: typeof SellerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/product-upgrader': {
      id: '/tools/product-upgrader'
      path: '/tools/product-upgrader'
      fullPath: '/tools/product-upgrader'
      preLoaderRoute: typeof ToolsProductUpgraderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CreditsRoute: CreditsRoute,
  ExploreRoute: ExploreRoute,
  SellerDashboardRoute: SellerDashboardRoute,
  ToolsProductUpgraderRoute: ToolsProductUpgraderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
